service: endpoints
runtime: python27
threadsafe: no
api_version: 1

env_variables:
  ROOMS_DEV_SIGNIN_EMAIL: rebuildingtogether.staff@gmail.com
#  ROOMS_DEV_SIGNIN_EMAIL: rebuildingtogether.capn@gmail.com

handlers:
- url: /js/lib
  static_dir: build/js/lib

- url: /js/app
  static_dir: app/js

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /room/rest/.*
  script: room/rest_main.py
  login: required

- url: /room/partials
  static_dir: room/partials

# Endpoints handler
- url: /_ah/spi/.*
  script: room.api.application

- url: /.*
  script: main.app

builtins:
- remote_api: on
- deferred: on

libraries:
- name: endpoints
  version: 1.0
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"