service: default
runtime: python27
threadsafe: no
api_version: kate_testing

env_variables:
  ROOMS_DEV_SIGNIN_EMAIL: rebuildingtogether.nobody@gmail.com
#  ROOMS_DEV_SIGNIN_EMAIL: rebuildingtogether.staff@gmail.com
#  ROOMS_DEV_SIGNIN_EMAIL: rebuildingtogether.capn@gmail.com

handlers:
- url: /js/lib
  static_dir: build/js/lib

- url: /css/lib
  static_dir: build/css

- url: /js/app
  static_dir: app/js

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  secure: always

# WSGI protorpc service handler
- url: /wsgi_service.*
  script: room.wsgi_service.application
  login: required
  secure: always

- url: /room/.*
  script: main.app
  login: required
  secure: always

# Welcome screen.
- url: /.*
  script: main.app
  secure: always

builtins:
- remote_api: on
- deferred: on

libraries:
- name: six
  version: "latest"
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^test.*$
- ^node_modules.*$
