application: rebuildingtogethercaptain-hrd
version: test27
runtime: python27
api_version: 1
threadsafe: false

libraries: 
- name: django
  version: "1.2"

handlers:
- url: /static
  static_dir: static

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /room/js
  static_dir: room/js

- url: /room/admin/.*
  script: main.py
  login: admin

- url: /room/data/.*
  script: room.data.app
  login: required

- url: /room/rest/.*
  script: room/rest_main.py
  login: required

- url: /room/plain_models/.*
  script: room/plain_models.py
  login: required

- url: /room/partials
  static_dir: room/partials

- url: /room/.*
  script: main.py
  login: required

- url: /_ah/warmup
  script: main.py

- url: /.*
  script: main.py

builtins:
- remote_api: on
- deferred: on

inbound_services:
- warmup