application: rebuildingtogethercaptain-hrd
version: endpoints1
runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /room/rest/.*
  script: room/rest_main.py
  login: required

- url: /room/partials
  static_dir: room/partials

- url: /*
  script: main.app

builtins:
- remote_api: on
- deferred: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"