application: rebuildingtogethercaptain-hrd
version: issue209
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /room/admin/.*
  script: main.py
  login: admin

- url: /room/rest/.*
  script: room/rest_main.py
  login: required

- url: /room/partials
  static_dir: room/partials

- url: /room/.*
  script: main.py
  login: required

- url: /_ah/warmup
  script: main.py

- url: /.*
  script: main.py

builtins:
- datastore_admin: on
- remote_api: on
- deferred: on

inbound_services:
- warmup