version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
      
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install virtual env
          command: virtualenv ~/venv

      - run:
          name: install requirements.txt
          command: ./venv/bin/pip install -r requirements.txt

      - run:
          name: set google install non-interactive env var
          command: export CLOUDSDK_CORE_DISABLE_PROMPTS=1

      - run:
          name: curl google app engine
          command: curl https://sdk.cloud.google.com > /tmp/foo && . /tmp/foo --disable-prompts

      - run:
          name: install app-engine-python gcloud component
          command: ~/google-cloud-sdk/bin/gcloud components install app-engine-python

      - save_cache:
          paths: [~/venv]
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: set up PYTHONPATH
          command: export PYTHONPATH=/home/circleci/google-cloud-sdk/platform/google_appengine
            
      - run:
          name: run tests
          command: ~/venv/bin/python run_tests.py
      
      - store_artifacts:
          path: test-reports
          destination: test-reports

