service: default
runtime: python27
threadsafe: no
api_version: 1

env_variables:
  ROOMS_DEV_SIGNIN_EMAIL: rebuildingtogether.nobody@gmail.com
#  ROOMS_DEV_SIGNIN_EMAIL: rebuildingtogether.staff@gmail.com
#  ROOMS_DEV_SIGNIN_EMAIL: rebuildingtogether.capn@gmail.com

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# WSGI protorpc service API handlers.
- url: /cru_api.*
  script: room.cru_api.application
  login: required
  secure: always

- url: /choices_api.*
  script: room.choices_api.application
  login: required
  secure: always

- url: /custom_api.*
  script: room.custom_api.application
  login: required
  secure: always

- url: /staffposition_api.*
  script: room.staffposition_api.application
  login: required
  secure: always

# Handlers for most of the pages.
- url: /room/.*
  script: main.app
  login: required
  secure: always

# Welcome screen.
- url: /.*
  script: main.app
  secure: always

builtins:
- remote_api: on
- deferred: on

libraries:
- name: six
  version: "latest"
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^test.*$
- ^node_modules.*$
